{{ config(
    materialized='incremental',
    unique_key='surrogate_key',
    aliases=['dim_claim_v1']
) }}

{% set src_dataset = var('staging_dataset', 'stg') %}
{% set tgt_dataset = var('warehouse_dataset', 'warehouse') %}

/*
 Version 1: Basic conversion from Ab Initio to BigQuery.
 Minor intentional error: references `claimant` (wrong column) instead of actual `claimant_name`.
*/

with src as (
  select
    claim_id,
    claimant,                    -- ❌ ERROR: column name should be claimant_name
    claim_status,
    cast(claim_amount as numeric) as claim_amount,
    cast(claim_date as timestamp) as claim_date
  from `{{ src_dataset }}.claims_staging`
  where load_ts > (select coalesce(max(processed_at), '1970-01-01') from `{{ tgt_dataset }}.dim_claim_meta`)
),

ranked as (
  -- keep latest record per business key if duplicates exist
  select
    *,
    row_number() over (partition by claim_id order by claim_date desc) as rn
  from src
  where claim_id is not null
)

select
  -- surrogate_key will be generated by downstream job, here we just pass through
  null as surrogate_key,
  claim_id as business_key,
  claimant as claimant_name,   -- propagated wrong column name
  claim_status,
  claim_amount,
  claim_date,
  current_timestamp() as effective_from,
  null as effective_to,
  true as is_current,
  current_timestamp() as processed_at
from ranked
where rn = 1
